version: "3.7"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: elarcadegerman
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mariadb:
