CREATE DATABASE IF NOT EXISTS PPAI_DB;
USE PPAI_DB;

CREATE TABLE IF NOT EXISTS CARACTERISTICAS_RT (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARACTERISTICAS_RT PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TIPOS_RECURSO_TECNOLOGICO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_RECURSO_TECNOLOGICO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MODELOS (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT MODELOS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MARCAS (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MARCAS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RECURSOS_TECNOLOGICOS (
    ID INT NOT NULL AUTO_INCREMENT,
    NRO_INVENTARIO INT NOT NULL,
    FECHA_ALTA DATE,
    TIPO_RT INT NOT NULL,
    IMAGENES VARCHAR(100) NOT NULL,
    PERIODICIDAD_MP VARCHAR(100),
    DURACION_MP VARCHAR(100),
    NOMBRE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_RECURSOS_TECNOLOGICOS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CENTROS_DE_INVESTIGACION (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    SIGLA VARCHAR(100) NOT NULL,
    DIRECCION INT NOT NULL,
    TELEFONO INT NOT NULL,
    CORREO_ELECTRONICO INT NOT NULL,
    TIEMPO_PREVIO_RESERVA VARCHAR(100),
    FECHA_INICIO DATE,
    ESTADO INT NOT NULL,
    FECHA_BAJA DATE,
    MOTIVO_BAJA VARCHAR(200),
    NRO_RESOLUCION INT,
    FECHA_RESOLUCION DATE,
    REGLAMENTO VARCHAR(100),
    FECHA_ALTA DATE,
    DIRECTOR INT NOT NULL,
    CONSTRAINT PK_CENTROS_DE_INVESTIGACION PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ESTADOS (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ESTADOS PRIMARY KEY(ID)
);


